Repository BuildForSDGCohort2/coffee-port-server, pull requests merged in 2020-09, with the labels that each got.

#15 feat: add create product mutation and get all products query
  src/index.js
  src/models/Product.js
  src/resolvers/product.js
  src/schema/company.js
  src/schema/index.js
  src/schema/product.js
  src/schema/user.js
Labels: enhancement

#23 Develop benyam
  src/index.js
  src/models/Product.js
  src/models/User.js
  src/resolvers/authorization.js
  src/resolvers/product.js
  src/resolvers/user.js
  src/schema/errors.js
  src/schema/product.js
  src/schema/user.js
  src/util/helpers.js
  src/util/validators.js
Labels: enhancement

#24 feat: added product, updateProduct and updated products to be filterd
  package-lock.json
  package.json
  src/resolvers/product.js
  src/schema/errors.js
  src/schema/product.js
Labels: enhancement

#26 fix: added the middlewares for updateProduct again
  src/resolvers/product.js
Labels: bug

#39 added validation for product mutation
  src/resolvers/product.js
  src/schema/errors.js
  src/schema/product.js
  src/schema/user.js
  src/util/validators.js
Labels: enhancement

#42 added user query, deleteUser and updateUser (with validation)
  src/resolvers/user.js
  src/schema/company.js
  src/schema/errors.js
  src/schema/user.js
  src/util/validators.js
Labels: enhancement

#44 fix: fixed a bug which overwrites the unique attributes to null
  src/resolvers/product.js
Labels: bug

#51 Develop benyam
  src/models/Product.js
  src/models/User.js
  src/resolvers/authorization.js
  src/resolvers/product.js
  src/resolvers/review.js
  src/resolvers/user.js
  src/schema/company.js
  src/schema/errors.js
  src/schema/product.js
  src/schema/review.js
  src/schema/user.js
  src/util/validators.js
Labels: bug, enhancement

#58 added new features
  src/models/Product.js
  src/resolvers/product.js
  src/resolvers/user.js
  src/schema/errors.js
  src/schema/product.js
  src/schema/user.js
Labels: enhancement

#62 report user queries and mutation, isVerified middleware, email verification and new prodct attr
  package-lock.json
  package.json
  src/models/Product.js
  src/models/Report.js
  src/models/User.js
  src/models/index.js
  src/resolvers/authorization.js
  src/resolvers/index.js
  src/resolvers/product.js
  src/resolvers/report.js
  src/resolvers/user.js
  src/schema/errors.js
  src/schema/index.js
  src/schema/product.js
  src/schema/report.js
  src/schema/user.js
  src/util/helpers.js
  src/util/sendmail.js
  src/util/validators.js
Labels: enhancement

#66 resend confirmation email
  src/resolvers/user.js
  src/schema/errors.js
  src/schema/user.js
  src/util/sendmail.js
Labels: enhancement
